provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-covariate-extractor:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-covariate-extractor:0.2.5
    secrets:
      - ssl-cert
    environment:
      write_debug: true
      exec_timeout: 600
      write_timeout: 700
      read_timeout: 700
      combine_output: false
      http_proxy: squid:3128
      https_proxy: squid:4128
      CURL_CA_BUNDLE: /var/openfaas/secrets/ssl-cert
