provider:
  name: faas
  gateway: http://faas.srv.disarm.io
functions:
  fn-covariate-extractor:
    lang: dockerfile
    handler: ./fn-covariate-extractor
    image: disarm/fn-covariate-extractor:latest
    environment:
      write_debug: true
      write_timeout: 60
      combine_output: false