provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-covariate-extractor:
    lang: dockerfile
    handler: ./fn-covariate-extractor
    image: disarm/fn-covariate-extractor:0.0.5
    environment:
      # write_debug: true
      exec_timeout: 60
      write_timeout: 70
      read_timeout: 70
      combine_output: false
